import Head from "next/head"
import Link from "next/link"
import React from "react"

const Quiz: React.FC = () => {
  
  return (
    <>
      <Head>
        <title>Next Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button>START</button>
      <Link href='/'>ホームに戻る</Link>
    </>
  )
}

export default Quiz